### ISSUE TITLE
Available functionality

### ISSUE THREAD

**Issue by kuraga** [afparsons/doccano_api_client#1]
@afparsons , thanks for your work!

Is it correct functionality like deleting isn't available?

**Comment by afparsons** [comment]
@kuraga No problem! 

> Is it correct functionality like deleting isn't available?

I'm not sure; I will try to check in the next few days. A few things to note:
- everything I know about the endpoints is listed in the [README.md](https://github.com/afparsons/doccano_api_client/blob/master/README.md) file. 
- this was supposed to be a temporary solution! I guess the doccano team hasn't yet [made their own client](https://github.com/doccano/doccano/issues/299#issuecomment-557037552)?
- I based the API client code off of what I could find in [doccano's source code](https://github.com/doccano/doccano/blob/master/app/api/urls.py), but I wasn't able to find much documentation to begin with.
- I originally created this API client to quickly solve a problem I had at work; the [supported endpoints](https://github.com/afparsons/doccano_api_client/blob/master/README.md#completion) came in order of my own personal requirement!

Please let me know if you find a way to get deletion to work so that I can add it to the client.

**Comment by afparsons** [comment]
It sounds like another user has implemented this endpoint in Issue https://github.com/afparsons/doccano_api_client/issues/5 and is hoping to merge their change.
